Concatenate error???
Traceback (most recent call last):
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 468, in <module>
    model = lstm_model(-1, EMBEDDING_DIM, embedding_W, len(dictionary_object.word2id_dic)) #fix 
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 126, in lstm_model
    encoded_info = Merge()([encode_left_drop, encode_mid_drop, encode_right_drop])
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 11, 1000), (None, 300), (None, 11, 1000)]