update Merge
Using TensorFlow backend.
=== SCALE_LOSS_FUN: 1, ONE_SIDE_CONTEXT_SIZE: 10 ===
NOTE: Make sure you have MIN_SENTENCES_IN_DOCUMENT >= 2*context_size + 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total WIKIPEDIA(test) data: 300 chapters, 2265 paragraphs and 58578 sentences
Samples Loading took 0.114676952362 seconds
Loading word2vec model
/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
tcmalloc: large alloc 3600007168 bytes == 0x555ec0a8e000 @  0x7fe65b5af001 0x7fe6593c5895 0x7fe65942a207 0x7fe65942c26f 0x7fe6594c4940 0x555eb7f09feb 0x555eb7efed5a 0x555eb7f0686e 0x555eb7efed5a 0x555eb7f0686e 0x555eb7efed5a 0x555eb7f1abc9 0x555eb7f32efe 0x555eb7f32b2a 0x555eb7eefa0b 0x555eb7f066c0 0x555eb7efed5a 0x555eb7f0686e 0x555eb7efed5a 0x555eb7efe899 0x555eb7f2f0ef 0x555eb7f2a2f2 0x555eb7f29ded 0x555eb7ed8c99 0x7fe65b1aabf7 0x555eb7ed862a
Model Loaded!
300
Creating a standalone matrix for samples... ...                              
Total samples: 300
SHUFFLE: Shuffled input document order! (X: (300,) , Y: (300,) )
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total BIOGRAPHY data: 11 chapters, 298 paragraphs and 2285 sentences
Samples Loading took 0.0152978897095 seconds
1
Creating a standalone matrix for samples... ...                              
Total samples: 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total CLINICAL data: 227 chapters, 909 paragraphs and 31868 sentences
Samples Loading took 0.117937088013 seconds
227
Creating a standalone matrix for samples... ...                              
Total samples: 227
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
##### Loading FICTION: testing data ######
Total FICTION data: 82 chapters, 1245 paragraphs and 27551 sentences
Samples Loading took 0.263022184372 seconds
82
Creating a standalone matrix for samples... ...                              
Total samples: 82
"word '<UNK>' not in vocabulary"
1 embedding missed
#####################################################################
VOCAB_SIZE: 80620
#####################################################################
Build MAIN model...
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:83: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  context_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:84: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  main_input_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
2021-04-18 13:49:51.892801: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-18 13:49:51.985427: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-18 13:49:51.985608: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (5ff3a1beb484): /proc/driver/nvidia/version does not exist
2021-04-18 13:49:52.076791: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2299995000 Hz
2021-04-18 13:49:52.077648: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555fa12e0680 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-18 13:49:52.077699: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-2gram", activation="tanh", padding="same", filters=200, kernel_size=2)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-3gram", activation="tanh", padding="same", filters=200, kernel_size=3)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-4gram", activation="tanh", padding="same", filters=200, kernel_size=4)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-5gram", activation="tanh", padding="same", filters=200, kernel_size=5)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
Traceback (most recent call last):
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 468, in <module>
    model = lstm_model(-1, EMBEDDING_DIM, embedding_W, len(dictionary_object.word2id_dic))
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 110, in lstm_model
    convoluted_left, convoluted_mid, convoluted_right = Merge(mode='concat')(convsL), Merge(mode='concat')(convsM), Merge(mode='concat')(convsR)
TypeError: concatenate() takes at least 1 argument (0 given)