fix add_weight()
Using TensorFlow backend.
=== SCALE_LOSS_FUN: 1, ONE_SIDE_CONTEXT_SIZE: 10 ===
NOTE: Make sure you have MIN_SENTENCES_IN_DOCUMENT >= 2*context_size + 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total WIKIPEDIA(test) data: 300 chapters, 2265 paragraphs and 58578 sentences
Samples Loading took 0.15763092041 seconds
Loading word2vec model
/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
tcmalloc: large alloc 3600007168 bytes == 0x561b6dda6000 @  0x7fe80b749001 0x7fe80955f895 0x7fe8095c4207 0x7fe8095c626f 0x7fe80965e940 0x561b6692efeb 0x561b66923d5a 0x561b6692b86e 0x561b66923d5a 0x561b6692b86e 0x561b66923d5a 0x561b6693fbc9 0x561b66957efe 0x561b66957b2a 0x561b66914a0b 0x561b6692b6c0 0x561b66923d5a 0x561b6692b86e 0x561b66923d5a 0x561b66923899 0x561b669540ef 0x561b6694f2f2 0x561b6694eded 0x561b668fdc99 0x7fe80b344bf7 0x561b668fd62a
Model Loaded!
300
Creating a standalone matrix for samples... ...                              
Total samples: 300
SHUFFLE: Shuffled input document order! (X: (300,) , Y: (300,) )
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total BIOGRAPHY data: 11 chapters, 298 paragraphs and 2285 sentences
Samples Loading took 0.0122680664062 seconds
1
Creating a standalone matrix for samples... ...                              
Total samples: 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total CLINICAL data: 227 chapters, 909 paragraphs and 31868 sentences
Samples Loading took 0.116320848465 seconds
227
Creating a standalone matrix for samples... ...                              
Total samples: 227
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
##### Loading FICTION: testing data ######
Total FICTION data: 82 chapters, 1245 paragraphs and 27551 sentences
Samples Loading took 0.251868009567 seconds
82
Creating a standalone matrix for samples... ...                              
Total samples: 82
"word '<UNK>' not in vocabulary"
1 embedding missed
#####################################################################
VOCAB_SIZE: 80620
#####################################################################
Build MAIN model...
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:83: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  context_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:84: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  main_input_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
2021-04-23 16:59:50.628816: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-23 16:59:50.729951: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-23 16:59:50.730061: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (d4b8f195fce0): /proc/driver/nvidia/version does not exist
2021-04-23 16:59:50.825536: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200140000 Hz
2021-04-23 16:59:50.826329: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x561c4e5f8680 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-23 16:59:50.826404: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-2gram", activation="tanh", padding="same", filters=200, kernel_size=2)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-3gram", activation="tanh", padding="same", filters=200, kernel_size=3)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-4gram", activation="tanh", padding="same", filters=200, kernel_size=4)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-5gram", activation="tanh", padding="same", filters=200, kernel_size=5)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:116: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(500, recurrent_dropout=0.2, implementation=2, dropout=0.2, input_shape=(10, 800), stateful=False, return_sequences=True)`
  context_encoder_intermediate1 = Bidirectional(LSTM(500, input_shape=(ONE_SIDE_CONTEXT_SIZE, CONV_DIM), consume_less='gpu', dropout_W=0.2, dropout_U=0.2, return_sequences=True, stateful=False), name='BiLSTM-context-encoder-intermediate1', merge_mode='concat')
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:118: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(500, recurrent_dropout=0.2, implementation=2, dropout=0.2, input_shape=(10, 800), stateful=False, return_sequences=True)`
  context_encoder = Bidirectional(LSTM(500, input_shape=(ONE_SIDE_CONTEXT_SIZE, CONV_DIM), consume_less='gpu', dropout_W=0.2, dropout_U=0.2, return_sequences=True, stateful=False), name='BiLSTM-context-encoder', merge_mode='concat')
Traceback (most recent call last):
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 468, in <module>
    model = lstm_model(-1, EMBEDDING_DIM, embedding_W, len(dictionary_object.word2id_dic))
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 122, in lstm_model
    encode_left = AttentionWithContext(name='encode-left-attention')(context_encoder(context_encoder_intermediate1(convoluted_left)))
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/content/neuralTextSegmentation/code/AttentionWithContext.py", line 52, in build
    constraint=self.W_constraint)
TypeError: add_weight() got multiple values for keyword argument 'name'