ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis.
Using TensorFlow backend.
=== SCALE_LOSS_FUN: 1, ONE_SIDE_CONTEXT_SIZE: 10 ===
NOTE: Make sure you have MIN_SENTENCES_IN_DOCUMENT >= 2*context_size + 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total WIKIPEDIA(test) data: 300 chapters, 2265 paragraphs and 58578 sentences
Samples Loading took 0.144915819168 seconds
Loading word2vec model
/usr/local/lib/python2.7/dist-packages/smart_open/smart_open_lib.py:398: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL
tcmalloc: large alloc 3600007168 bytes == 0x55a49075c000 @  0x7f1105676001 0x7f110348c895 0x7f11034f1207 0x7f11034f326f 0x7f110358b940 0x55a489870feb 0x55a489865d5a 0x55a48986d86e 0x55a489865d5a 0x55a48986d86e 0x55a489865d5a 0x55a489881bc9 0x55a489899efe 0x55a489899b2a 0x55a489856a0b 0x55a48986d6c0 0x55a489865d5a 0x55a48986d86e 0x55a489865d5a 0x55a489865899 0x55a4898960ef 0x55a4898912f2 0x55a489890ded 0x55a48983fc99 0x7f1105271bf7 0x55a48983f62a
Model Loaded!
300
Creating a standalone matrix for samples... ...                              
Total samples: 300
SHUFFLE: Shuffled input document order! (X: (300,) , Y: (300,) )
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total BIOGRAPHY data: 11 chapters, 298 paragraphs and 2285 sentences
Samples Loading took 0.00958180427551 seconds
1
Creating a standalone matrix for samples... ...                              
Total samples: 1
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
Total CLINICAL data: 227 chapters, 909 paragraphs and 31868 sentences
Samples Loading took 0.116506099701 seconds
227
Creating a standalone matrix for samples... ...                              
Total samples: 227
#### Using split type: section
==== MIN_SENTENCES_IN_DOCUMENT: 21, MIN_SENTENCES_IN_SECTION: 1, MIN_SECTIONS(excluding 1st): 2, MIN_SENTENCES_IN_PARAGRAPH: -1 ===
===========================================
##### Loading FICTION: testing data ######
Total FICTION data: 82 chapters, 1245 paragraphs and 27551 sentences
Samples Loading took 0.24033498764 seconds
82
Creating a standalone matrix for samples... ...                              
Total samples: 82
"word '<UNK>' not in vocabulary"
1 embedding missed
#####################################################################
VOCAB_SIZE: 80620
#####################################################################
Build MAIN model...
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:83: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  context_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:84: UserWarning: Update your `Embedding` call to the Keras 2 API: `Embedding(80621, 300, embeddings_initializer="uniform", weights=[array([[ ..., input_length=20)`
  main_input_embedder = TimeDistributed(Embedding(vocab_size + 1, GLOVE_EMBEDDING_DIM, weights=[embedding_matrix], input_length=embedding_dim, init='uniform'))
2021-04-24 02:21:02.043274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-24 02:21:02.126925: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-04-24 02:21:02.127079: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (11e383d0bcc4): /proc/driver/nvidia/version does not exist
2021-04-24 02:21:02.225174: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200160000 Hz
2021-04-24 02:21:02.226044: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55a5710219c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-24 02:21:02.226107: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-2gram", activation="tanh", padding="same", filters=200, kernel_size=2)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-3gram", activation="tanh", padding="same", filters=200, kernel_size=3)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-4gram", activation="tanh", padding="same", filters=200, kernel_size=4)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:93: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(name="Convolution-5gram", activation="tanh", padding="same", filters=200, kernel_size=5)`
  activation='tanh', name='Convolution-'+str(n_gram)+"gram")
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:116: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(500, recurrent_dropout=0.2, implementation=2, dropout=0.2, input_shape=(10, 800), stateful=False, return_sequences=True)`
  context_encoder_intermediate1 = Bidirectional(LSTM(500, input_shape=(ONE_SIDE_CONTEXT_SIZE, CONV_DIM), consume_less='gpu', dropout_W=0.2, dropout_U=0.2, return_sequences=True, stateful=False), name='BiLSTM-context-encoder-intermediate1', merge_mode='concat')
/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py:118: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(500, recurrent_dropout=0.2, implementation=2, dropout=0.2, input_shape=(10, 800), stateful=False, return_sequences=True)`
  context_encoder = Bidirectional(LSTM(500, input_shape=(ONE_SIDE_CONTEXT_SIZE, CONV_DIM), consume_less='gpu', dropout_W=0.2, dropout_U=0.2, return_sequences=True, stateful=False), name='BiLSTM-context-encoder', merge_mode='concat')
Traceback (most recent call last):
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 468, in <module>
    model = lstm_model(-1, EMBEDDING_DIM, embedding_W, len(dictionary_object.word2id_dic))
  File "/content/neuralTextSegmentation/code/lstm_try_with_highSegLenTrain.py", line 126, in lstm_model
    encoded_info = Merge([encode_left_drop, encode_mid_drop, encode_right_drop])
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/merge.py", line 649, in concatenate
    return Concatenate(axis=axis, **kwargs)(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/merge.py", line 362, in build
    'Got inputs shapes: %s' % (input_shape))
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 11, 1000), (None, 300), (None, 11, 1000)]